[package]
name = "create_event"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.15.2"
arrayref = "0.3.6"

[lib]
name = "buy_ticket"
crate-type = ["cdylib", "lib"]
