name: Deploy to Github Pages
on: 
  push:
    paths:
     - '**.js'
     - '**.css'
     - '**.html'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend